'use client';
import React,{useEffect,useState}from'react';
import{FolderSearch,FileText,Music,BookOpen,Send,Joystick,MapPin,BriefcaseBusiness}from'lucide-react';
import{profile,projects,contacts}from'../src/data';
const useLocal=(k,init)=>{const[v,setV]=useState(init);useEffect(()=>{try{const x=localStorage.getItem(k);if(x!==null)setV(JSON.parse(x))}catch{}},[]);useEffect(()=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},[k,v]);return[v,setV]};
export function Feature({id,onGame}){
 if(id==='about')return <About/>;
 if(id==='work')return <div className="projects">{projects.map(p=><article key={p.name}><small>{p.cat}</small><h3>{p.name}</h3><p>{p.desc}</p><b>{p.tech}</b><em>{p.status}</em></article>)}</div>;
 if(id==='resume')return <div className="empty"><FileText size={48}/><h2>RESUMO.PDF</h2><p>Currículo atualizado com a mesma base profissional do portfólio.</p><div className="fileactions"><a href="/resumo-mateus-araujo-santos.pdf" target="_blank" rel="noopener noreferrer">VISUALIZAR</a><a href="/resumo-mateus-araujo-santos.pdf" download>DOWNLOAD</a></div></div>;
 if(id==='contact')return <div className="contacts">{contacts.map(([name,url])=><a key={name} href={url} target="_blank" rel="noopener noreferrer"><Send size={18}/><b>{name}</b><span>↗</span></a>)}</div>;
 if(id==='music')return <div className="empty"><Music size={48}/><h2>MUSIC PLAYER</h2><p>Nenhuma faixa autorizada foi fornecida. Controles de áudio ficam ocultos até existir mídia legítima.</p></div>;
 if(id==='clippy')return <div className="empty"><div className="clipface small"><i/><i/></div><h2>CLIP AJUDA</h2><p>Olá, Mateus! Posso apresentar o desktop, lembrar que a Viagem no Tempo leva ao MATEUS SPACE e indicar onde estão currículo, formação e contatos.</p></div>;
 if(id==='guest')return <Guest/>;
 if(id==='aims')return <Aims/>;
 if(id==='games')return <GameCenter onGame={onGame}/>;
 return null;
}
function About(){return <div className="profile"><h1>{profile.name}</h1><p className="tagline">{profile.title}</p><p><MapPin size={16}/>{profile.location}</p><p className="lead">{profile.intro}</p><h3>EXPERIÊNCIA PROFISSIONAL</h3><div className="experience"><BriefcaseBusiness/><div><b>{profile.experience.organization}</b><small>{profile.experience.period}</small><p>{profile.experience.summary}</p><ul>{profile.experience.skills.map(x=><li key={x}>{x}</li>)}</ul></div></div><h3>FORMAÇÃO</h3>{profile.education.map(x=><div className="row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}<h3>ESPECIALIZAÇÕES</h3>{profile.specializations.map(x=><div className="row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div>}
function Aims(){const[msgs,setMsgs]=useState([{from:'SYSTEM',text:'Mateus está online.'},{from:'MATEUS',text:'Escolha uma resposta rápida.'}]);const send=t=>setMsgs(m=>[...m,{from:'VOCÊ',text:t},{from:'MATEUS',text:t.includes('projetos')?'Projetos reais aparecerão no explorador assim que forem publicados.':'Minha trajetória conecta logística, gestão e inteligência artificial.'}]);return <div className="chat"><div>{msgs.map((m,i)=><p key={i}><b>{m.from}:</b> {m.text}</p>)}</div><footer><button onClick={()=>send('Conte sobre sua trajetória')}>TRAJETÓRIA</button><button onClick={()=>send('Quais projetos estão ativos?')}>PROJETOS</button></footer></div>}
function Guest(){const[posts,setPosts]=useLocal('mateus-guestbook',[]),[name,setName]=useState(''),[text,setText]=useState(''),[status,setStatus]=useState('');const submit=e=>{e.preventDefault();let n=name.trim().replace(/[<>]/g,''),t=text.trim().replace(/[<>]/g,'');if(n.length<2||t.length<3)return setStatus('Preencha nome e comentário.');if(posts[0]?.name===n&&posts[0]?.text===t)return setStatus('Assinatura duplicada bloqueada.');let last=Number(localStorage.getItem('guest-last')||0);if(Date.now()-last<8000)return setStatus('Aguarde alguns segundos.');setPosts(p=>[{name:n,text:t,date:new Date().toLocaleString('pt-BR')},...p].slice(0,30));localStorage.setItem('guest-last',Date.now());setName('');setText('');setStatus('Assinatura salva neste dispositivo.')};return <div className="guest"><BookOpen size={36}/><form onSubmit={submit}><label>Nome ou apelido<input maxLength={32} value={name} onChange={e=>setName(e.target.value)}/></label><label>Comentário<textarea maxLength={280} value={text} onChange={e=>setText(e.target.value)}/></label><button>ASSINAR LIVRO</button><small>{status}</small></form><div>{posts.length?posts.map((p,i)=><article key={i}><b>{p.name}</b><time>{p.date}</time><p>{p.text}</p></article>):<p>Nenhuma assinatura neste dispositivo.</p>}</div></div>}
function GameCenter({onGame}){return <div className="gamecenter"><p>Jogos disponíveis e funcionais:</p>{[['Snake OS','WASD / setas','snake'],['Campo Minado','Mouse / touch','mines']].map(x=><button key={x[2]} onClick={()=>onGame?.(x[2])}><Joystick/><b>{x[0]}</b><small>{x[1]}</small><em>JOGAR</em></button>)}</div>}
