export const profile={
 name:'Mateus Araujo Santos',displayName:'MATEUS',location:'Brasília, Distrito Federal, Brasil',
 title:'Logística & Supply Chain | Gestão Pública | Tecnologia & IA',
 intro:'Sou graduado em Tecnologia em Logística, com formação complementar em Logística e Supply Chain Management, Licitações e Contratos Administrativos, Gestão Pública, Finanças e Controladoria. Minha experiência profissional contribuiu para o desenvolvimento de competências em organização, controle documental, rotinas administrativas e cumprimento de procedimentos. Também venho ampliando meus conhecimentos em tecnologia e Inteligência Artificial, explorando aplicações para produtividade, processos e soluções digitais.',
 education:[['Tecnologia em Logística - Concluído','Centro Universitário IESB'],['Operador de Computador com Inteligência Artificial - 160h','SENAI'],['Contabilidade Básica - 30h','IFRS'],['Gestão Financeira - 40h','IFRS']],
 specializations:['MBA em Logística e Supply Chain Management','MBA em Finanças e Controladoria','MBA em Gestão Pública','Pós-graduação em Licitações e Contratos Administrativos'].map(x=>[x,'Anhanguera']),
 experience:{organization:'Exército Brasileiro',period:'2019 - atual',summary:'Atuação em rotinas administrativas, organização e controle documental, elaboração e acompanhamento de documentos, atualização de informações e suporte às atividades da seção.',skills:['Organização administrativa','Gestão documental','Controle de informações','Cumprimento de prazos e procedimentos','Comunicação entre setores','Acompanhamento de demandas','Trabalho em equipe']}
};
export const skills=['Logística','Supply Chain Management','Gestão de Documentos','Rotinas Administrativas','Gestão de Informações','Organização','Microsoft Office','Gestão Pública','Administração Pública','Finanças e Controladoria','Planejamento','Inteligência Artificial','Engenharia de Prompt','Ferramentas Digitais','Produtividade com IA','Comunicação','Trabalho em Equipe'];
export const projects=[{name:'MATEUS OS 00 → MATEUS SPACE',cat:'PORTFÓLIO PESSOAL INTERATIVO',desc:'Portfólio que conecta a estética dos computadores dos anos 2000 a uma experiência digital moderna. A Viagem no Tempo transforma o desktop retrô em um ambiente espacial com partículas e interfaces tecnológicas.',tech:'IA assistida · Engenharia de Prompt · Desenvolvimento Web · UI/UX · Responsividade',status:'PROJETO PRINCIPAL'}];
export const now=['ESTUDANDO · Inteligência Artificial, Engenharia de Prompt, Licitações e Tecnologia','CONSTRUINDO · Portfólio pessoal interativo, projetos digitais e experimentos com IA','EXPLORANDO · IA aplicada à produtividade e desenvolvimento web assistido','OBJETIVOS · Aplicar a formação acadêmica e ampliar competências profissionais e tecnológicas'];
export const contacts=[['LinkedIn Oficial','https://www.linkedin.com/in/mateus-araujo-santos'],['GitHub','https://github.com/matteusimpor-arch']];
export const apps=[['about','Sobre Mim','Trajetória • Formação • Perfil','UserRound'],['skills','O Que Eu Faço','Competências • Sistemas • Gestão','Cpu'],['work','Trabalho Selecionado','Projetos • Estudos • Explorar','FolderOpen'],['resume','Resumo.pdf','Currículo • Formação • Download','FileText'],['now','Agora (2026)','Status • Estudos • Objetivos','Activity'],['aims','AIMS','Mensagens • Presença • Conexão','MessageSquare'],['games','Jogos','Arcade • Estratégia • Reflexos','Gamepad2'],['contact','Contato','Canais diretos • Conectar','Radio']];
